# Generated by Django 2.1 on 2018-08-16 09:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.get_captchas_date_based_path),
        ),
    ]
