# Generated by Django 2.1 on 2018-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='session_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='answer',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='md5',
            field=models.CharField(max_length=32),
        ),
    ]
