# Generated by Django 2.2.4 on 2019-08-18 12:13

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rinja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='session_id',
            field=models.CharField(default='asd', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='md5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nominal_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
    ]
