# Generated by Django 2.2.4 on 2019-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinja', '0002_auto_20190818_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.ImageField(upload_to='media/captchas/'),
        ),
    ]
