# Generated by Django 2.2.4 on 2019-08-18 20:32

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rinja', '0005_auto_20190818_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='latest_market_share_price',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='latest_market_share_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='latest_real_market_cap',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='latest_real_market_cap_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nominal_market_cap',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nominal_market_cap_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nominal_share_price',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nominal_share_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='ASD1T', max_length=5),
            preserve_default=False,
        ),
    ]
