# Generated by Django 2.2.5 on 2019-10-02 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rinja', '0007_auto_20190818_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='session_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
