# Generated by Django 2.2.5 on 2019-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rinja', '0008_auto_20191002_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
