# Generated by Django 2.2.12 on 2020-04-06 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enum_choices.choice_builders
import django_enum_choices.fields
import rinja.models


class Migration(migrations.Migration):

    dependencies = [
        ('rinja', '0010_remove_stockposition_at_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issuer_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='issuer_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockposition',
            name='checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockposition',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockPositionNetChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('buy', 'buy'), ('sell', 'sell')], enum_class=rinja.models.StockPositionChangeTypes, max_length=4)),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stock_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinja.StockPosition')),
            ],
        ),
    ]
